# ~/.config/starship.toml

# Character section
[character]
success_symbol = "[✔](bold green)"
error_symbol = "[✘](bold red)"

# Time configuration
[time]
format = "[$time]($style)"
style = "bold yellow fg:#f1fa8c"  # Yellow color for the time

# Directory configuration
[directory]
style = "bold fg:#bd93f9"  # Purple color for directories in Dracula theme
truncation_length = 2
home_symbol = "🏠 "  # Home directory symbol

# Git Branch configuration
[git_branch]
symbol = " "
style = "bold fg:#8be9fd"  # Light cyan color for the Git branch

# Git Status configuration
[git_status]
style = "bold fg:#ff79c6"  # Pink color for the git status (modified, added, etc.)

# Virtual Environment Configuration (Python)
[python]
style = "bold fg:#ffb86c"  # Yellow for Python virtual environment icon

# Custom user info (Whoami command)
[custom.user_info]
command = "whoami"
style = "fg:#8be9fd"  # Light cyan for the user info